# Generated by Django 4.2.2 on 2023-06-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("live_tracker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("genre", models.CharField(max_length=50)),
            ],
        ),
    ]
