# Generated by Django 4.2.2 on 2023-06-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("live_tracker", "0002_artist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artist",
            name="genre",
        ),
        migrations.AlterField(
            model_name="artist",
            name="id",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
